// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWy2tfzTMDuW_LaCDOY47c7b0yOKWguU',
    appId: '1:625855875282:android:9191f3f77760fff35f850b',
    messagingSenderId: '625855875282',
    projectId: 'brokkerspot-6bc24',
    storageBucket: 'brokkerspot-6bc24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0va3NiT4C_JdY5Dm1adzaqfMgr_t6PM',
    appId: '1:625855875282:ios:05db4f26f64e62d35f850b',
    messagingSenderId: '625855875282',
    projectId: 'brokkerspot-6bc24',
    storageBucket: 'brokkerspot-6bc24.firebasestorage.app',
    androidClientId: '625855875282-gu4ggo821o7l31vnu5h8qbid49mte6h3.apps.googleusercontent.com',
    iosClientId: '625855875282-54mq74pcdrpeppadf6986kbarp9jjblb.apps.googleusercontent.com',
    iosBundleId: 'com.brokersport.app',
  );
}
