/// Dial codes offered by the phone-number fields.
///
/// Shared so every screen that asks for a phone number offers the same list —
/// it previously lived inside SignupView, which left NeedHelpView with a
/// hardcoded UAE flag and no way to pick anything else.
const List<Map<String, String>> kCountryDialCodes = [
    {'flag': '🇦🇪', 'code': '+971'},
    {'flag': '🇮🇳', 'code': '+91'},
    {'flag': '🇺🇸', 'code': '+1'},
    {'flag': '🇬🇧', 'code': '+44'},
    {'flag': '🇦🇺', 'code': '+61'},
    {'flag': '🇸🇦', 'code': '+966'},
    {'flag': '🇶🇦', 'code': '+974'},
    {'flag': '🇰🇼', 'code': '+965'},
    {'flag': '🇧🇭', 'code': '+973'},
    {'flag': '🇴🇲', 'code': '+968'},
    {'flag': '🇪🇬', 'code': '+20'},
    {'flag': '🇯🇴', 'code': '+962'},
    {'flag': '🇱🇧', 'code': '+961'},
    {'flag': '🇮🇶', 'code': '+964'},
    {'flag': '🇵🇰', 'code': '+92'},
    {'flag': '🇧🇩', 'code': '+880'},
    {'flag': '🇱🇰', 'code': '+94'},
    {'flag': '🇳🇵', 'code': '+977'},
    {'flag': '🇵🇭', 'code': '+63'},
    {'flag': '🇮🇩', 'code': '+62'},
    {'flag': '🇲🇾', 'code': '+60'},
    {'flag': '🇸🇬', 'code': '+65'},
    {'flag': '🇹🇭', 'code': '+66'},
    {'flag': '🇻🇳', 'code': '+84'},
    {'flag': '🇨🇳', 'code': '+86'},
    {'flag': '🇯🇵', 'code': '+81'},
    {'flag': '🇰🇷', 'code': '+82'},
    {'flag': '🇩🇪', 'code': '+49'},
    {'flag': '🇫🇷', 'code': '+33'},
    {'flag': '🇮🇹', 'code': '+39'},
    {'flag': '🇪🇸', 'code': '+34'},
    {'flag': '🇵🇹', 'code': '+351'},
    {'flag': '🇳🇱', 'code': '+31'},
    {'flag': '🇧🇪', 'code': '+32'},
    {'flag': '🇨🇭', 'code': '+41'},
    {'flag': '🇦🇹', 'code': '+43'},
    {'flag': '🇸🇪', 'code': '+46'},
    {'flag': '🇳🇴', 'code': '+47'},
    {'flag': '🇩🇰', 'code': '+45'},
    {'flag': '🇫🇮', 'code': '+358'},
    {'flag': '🇵🇱', 'code': '+48'},
    {'flag': '🇬🇷', 'code': '+30'},
    {'flag': '🇹🇷', 'code': '+90'},
    {'flag': '🇷🇺', 'code': '+7'},
    {'flag': '🇺🇦', 'code': '+380'},
    {'flag': '🇿🇦', 'code': '+27'},
    {'flag': '🇳🇬', 'code': '+234'},
    {'flag': '🇰🇪', 'code': '+254'},
    {'flag': '🇬🇭', 'code': '+233'},
    {'flag': '🇪🇹', 'code': '+251'},
    {'flag': '🇲🇦', 'code': '+212'},
    {'flag': '🇹🇳', 'code': '+216'},
    {'flag': '🇧🇷', 'code': '+55'},
    {'flag': '🇲🇽', 'code': '+52'},
    {'flag': '🇦🇷', 'code': '+54'},
    {'flag': '🇨🇴', 'code': '+57'},
    {'flag': '🇨🇱', 'code': '+56'},
    {'flag': '🇵🇪', 'code': '+51'},
    {'flag': '🇳🇿', 'code': '+64'},
    {'flag': '🇮🇪', 'code': '+353'},
    {'flag': '🇮🇱', 'code': '+972'},
    {'flag': '🇭🇰', 'code': '+852'},
    {'flag': '🇹🇼', 'code': '+886'},
    {'flag': '🇲🇲', 'code': '+95'},
    {'flag': '🇦🇫', 'code': '+93'},
    {'flag': '🇮🇷', 'code': '+98'},
    {'flag': '🇾🇪', 'code': '+967'},
    {'flag': '🇸🇾', 'code': '+963'},
    {'flag': '🇱🇾', 'code': '+218'},
    {'flag': '🇸🇩', 'code': '+249'},
    {'flag': '🇩🇿', 'code': '+213'},
];
